# This file is generated by Anlogic Timing Wizard. 22 05 2019

#Created Clock
create_clock -name clk_24m -period 41.667 -waveform {0 20.8335} [get_ports {CLK_IN}]

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

