# This file is generated by Anlogic Timing Wizard. 29 04 2019

#Created Clock
create_clock -name clk_24m -period 41.667 -waveform {0 20.8335} [get_ports {CLK_IN}]

#Created Generated Clock
create_generated_clock  -name ccd_clk_100 -source [get_ports {CLK_IN}] -master_clock clk_24m -divide_by 100 [get_nets {ccd/clk_100}]

